title: Competition-Yellow-Pages
logo: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1568118393195&di=57addc90ad53482127d30a6ca755ea19&imgtype=0&src=http%3A%2F%2Fwww.dimeng.net%2Fuploads%2Fimage%2F2015%2F1231%2F20151231104246_26775.jpg
description: 南京邮电大学竞赛黄页
show_downloads: true

theme: jekyll-theme-minimal
